Fix ConvTranspose output padding on AMDGPU
This commit applies the output padding for ConvTranspose layers on
AMDGPU devices. Tests are added that ensure the output size is identical
to a ConvTranspose layer on the CPU.

In addition, this fixes the following test failure on AMDGPU:

  Convolution: Error During Test at /var/lib/buildkite-agent/builds/amdgpu1-luraess-com/julialang/flux-dot-jl/test/ext_amdgpu/basic.jl:27
      Got exception outside of a @test
      MethodError: no method matching ConvTranspose(::typeof(identity), ::ROCArray{Float32, 3, AMDGPU.Runtime.Mem.HIPBuffer}, ::ROCArray{Float32, 1, AMDGPU.Runtime.Mem.HIPBuffer}, ::Tuple{Int64}, ::Tuple{Int64, Int64}, ::Tuple{Int64}, ::Int64)